### ISSUE TITLE
Should we remove tip branch from CI?

### ISSUE THREAD

**Issue by ifraixedes** [cycloidio/raws#14]
Although it doesn't hurt that the CI test with the [Go tip branch](https://github.com/cycloidio/raws/blob/master/.travis.yml#L5), it could notify of some errors that they are not present in the stable branch, although Go is quite stable in terms of backward compatibility it can cause that master stop to pass the CI checks and don't find them until the next PR as it has happened with #11 

Related with #13

**Comment by xlr-8** [comment]
Let's remove it. We will update the CI with newer versions whenever we need it, or need to ensure compatibility.
