### ISSUE TITLE
Should we always use the last Go stable version in the CI?

### ISSUE THREAD

**Issue by ifraixedes** [cycloidio/raws#15]
I'm wondering if we should always update the CI configuration to use the last Go stable version.

In such case, on each new stable release should we update the CI and do whatever fixing the changes in the release may require.

**Comment by xlr-8** [comment]
I guess it doesn't hurt to always use it to see the issues to come. I should have checked that it was only the tip that was failing, if the stable passes, then I believe we are fine.

**Comment by ifraixedes** [comment]
According the response in https://github.com/cycloidio/raws/issues/14#issuecomment-361192888 the answer to this question is **yes**.
